<?php
/**
 * @file
 * Install code for the Signage Signs feature.
 */

/**
 * Implements hook_install().
 */
function signage_signs_install() {
  // Populate the default signage sign pathauto pattern.
  variable_set('pathauto_node_signage_sign_pattern', '[node:og_group_ref]/[node:content-type]/[node:title]');
}

/**
 * Implements hook_uninstall().
 */
function signage_signs_uninstall() {
  variable_del('pathauto_node_signage_sign_pattern');
}
