<?php
/**
 * @file
 * signage_groups.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function signage_groups_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function signage_groups_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function signage_groups_node_info() {
  $items = array(
    'signage_group' => array(
      'name' => t('Group'),
      'base' => 'node_content',
      'description' => t('A group is used to manage a set of signs.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
